Add retries

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,4 +1,14 @@
 version: 2.1
+
+parameters:
+  lastFailed:
+    type: enum
+    default: 'onretry'
+    enum:
+      - 'onretry'
+      - 'yes'
+      - 'no'
+
 jobs:
   shard-run-test:
     docker:
@@ -6,13 +16,26 @@ jobs:
     parallelism: 3
     environment:
       PLAYWRIGHT_JUNIT_OUTPUT_NAME: results.xml
+      CURRENTS_DISCOVERY_LAST_RUN: test-results/.last-run.json
     steps:
+      - run: if [ "${CIRCLE_WORKFLOW_WORKSPACE_ID}" != "${CIRCLE_WORKSPACE_ID}" ]; then export IS_RETRY="true"; fi
       - checkout
       - run: npm ci
       - run: npx playwright install
       - run:
           name: Run tests
-          command: SHARD="$((${CIRCLE_NODE_INDEX}+1))"; npx pwc --key $CURRENTS_RECORD_KEY --project-id 0biWxT --ci-build-id=shard-$CIRCLE_WORKFLOW_ID --reporter=junit --shard=$SHARD/$CIRCLE_NODE_TOTAL
+          command: |
+            SHARD="$((${CIRCLE_NODE_INDEX}+1))/$CIRCLE_NODE_TOTAL"
+            if [ "<<pipeline.parameters.lastFailed>>" == "yes" ] || ([ "<<pipeline.parameters.lastFailed>>" == "onretry" ] && [ -n "${IS_RETRY}" ]); then
+              if [ -n "${IS_RETRY}" ]; then
+                SHARD="1/1"
+                EXTRA_CURRENTS_CLI_FLAGS="--tag shard:$CIRCLE_WORKFLOW_WORKSPACE_ID"
+                export CURRENTS_DISCOVERY_LAST_RUN=.currents-last-run.json
+              fi
+              # npx currents get-run --failed --project=example  --branch=$CI_COMMIT_REF_NAME --provider="pw" $EXTRA_CURRENTS_CLI_FLAGS > $CURRENTS_DISCOVERY_LAST_RUN
+              export EXTRA_PW_FLAGS="--last-failed"
+            fi
+            npx pwc --key $CURRENTS_RECORD_KEY --project-id 0biWxT  --tag "shard:$CIRCLE_WORKFLOW_WORKSPACE_ID" --ci-build-id=shard-$CIRCLE_WORKFLOW_ID --reporter=junit --shard=$SHARD $EXTRA_PW_FLAGS
       - store_test_results:
           path: results.xml
 
@@ -36,17 +59,22 @@ jobs:
     docker:
       - image: mcr.microsoft.com/playwright:v1.47.0
     parallelism: 3
-    environment:
-      PLAYWRIGHT_JUNIT_OUTPUT_NAME: results.xml
     steps:
+      - run: if [ "${CIRCLE_WORKFLOW_WORKSPACE_ID}" != "${CIRCLE_WORKSPACE_ID}" ]; then export IS_RETRY="true"; fi
       - checkout
       - run: npm ci
       - run: npx playwright install
       - run:
           name: Run tests
-          command: SHARD="$((${CIRCLE_NODE_INDEX}+1))"; npx pwc-p --key $CURRENTS_RECORD_KEY --project-id 0biWxT --reporter=junit --ci-build-id=or8n-$CIRCLE_WORKFLOW_ID
-      - store_test_results:
-          path: results.xml
+          command: |
+            if [ "<<pipeline.parameters.lastFailed>>" == "yes" ] || ([ "<<pipeline.parameters.lastFailed>>" == "onretry" ] && [ -n "${IS_RETRY}" ]); then
+              if [ -n "${IS_RETRY}" ]; then
+                EXTRA_CURRENTS_CLI_FLAGS="--tag or8n:$CIRCLE_WORKFLOW_WORKSPACE_ID"
+              fi
+              # npx currents get-run --failed --project=example  --branch=$CI_COMMIT_REF_NAME --provider="pw" > test-results/.last-run.json
+              export EXTRA_PW_FLAGS="--last-failed"
+            fi
+            npx pwc-p --key $CURRENTS_RECORD_KEY --project-id 0biWxT --tag "or8n:$CIRCLE_WORKFLOW_WORKSPACE_ID" --reporter=junit --ci-build-id=or8n-$CIRCLE_WORKFLOW_ID $EXTRA_PW_FLAGS
 
 # Invoke jobs via workflows
 workflows:
